resources:
- name: flight-school
  type: git
  source:
    uri: git@github.com:jamesggraf/flight-school.git
    branch: master
    private_key: {{github_private_key}}

jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/build.yml
